// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TakenlijstManager.Data;

#nullable disable

namespace TakenlijstManager.Migrations
{
    [DbContext(typeof(StorageContext))]
    [Migration("20250319202712_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.14");

            modelBuilder.Entity("TakenlijstManager.Models.TaakModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("Omvang")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Prioriteit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TakenLijst");
                });
#pragma warning restore 612, 618
        }
    }
}
